#spring:
#  datasource:
#    url: jdbc:h2:mem:

server:
  port : 8080
spring:
  profiles:
    default: dev1
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev2
